### ISSUE TITLE
Question about SAM algorithm sign

### ISSUE THREAD

**Issue by millstar324** [huanranchen/AdversarialAttacks#6]
In the 4th row in paper's SAM sudo code that corresponds to the MI_SAM code's first step, I can't understand why '-='is used . In paper's SAM sudo code '+=' is used but the real code used '-='. 
![plus](https://github.com/user-attachments/assets/f1aea262-f1a4-4aea-9e6f-03a832d9c909)
![minus](https://github.com/user-attachments/assets/efd8819c-7263-4d49-90a5-3f6db377a209)

**Comment by huanranchen** [comment]
Hi~
In the paper, we define the objective function as the negative cross-entropy loss, which we aim to minimize. However, in the code implementation, we set the objective function as the positive cross-entropy loss, where the goal is to maximize the loss. As a result, all the plus signs in the paper should be replaced with minus signs in the code implementation, and vice versa.
